# Generated by Django 6.0.4 on 2026-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('practice_name', models.CharField(blank=True, max_length=200)),
                ('years_qualified', models.PositiveIntegerField()),
                ('num_dentists', models.PositiveIntegerField()),
                ('specialisms', models.TextField(blank=True)),
                ('prev_claims', models.CharField(choices=[('None', 'None'), ('1', '1 claim'), ('2', '2 claims'), ('3+', '3 or more claims')], max_length=10)),
                ('claim_details', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('risk_summary', models.TextField(blank=True)),
                ('risk_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
